# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kitsch < Formula
  desc ""
  homepage "https://kitschprompt.com"
  version "0.0.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jwalton/kitsch/releases/download/v0.0.14/kitsch_Darwin_x86_64.tar.gz"
      sha256 "1623c0de41daaa8e03cb7914039f980ae8748bdb779833824da316ecde474ab4"

      def install
        bin.install "kitsch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jwalton/kitsch/releases/download/v0.0.14/kitsch_Darwin_arm64.tar.gz"
      sha256 "f1173b6138641e7715bf49f5df9f6b34a2e86c735a35609aab32166fe8fcaceb"

      def install
        bin.install "kitsch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jwalton/kitsch/releases/download/v0.0.14/kitsch_Linux_armv6.tar.gz"
      sha256 "b66b5db30ea2b848581ce606bd00b11229360eea18dce655faa9b12b777541c5"

      def install
        bin.install "kitsch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jwalton/kitsch/releases/download/v0.0.14/kitsch_Linux_arm64.tar.gz"
      sha256 "8041554c81bafbae908ee6dcb05f95a0be19e5ab8c7b718ccffb842cd8344908"

      def install
        bin.install "kitsch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jwalton/kitsch/releases/download/v0.0.14/kitsch_Linux_x86_64.tar.gz"
      sha256 "35f9e0c0fdd7b2e0b4416e2794a941b50096ba53feb30ac24fb67bafce5a876c"

      def install
        bin.install "kitsch"
      end
    end
  end

  def caveats
    <<~EOS
      ***************************************************************************

        Please run "kitsch setup" for details about how to configure your shell
        to use kitsch.

      ***************************************************************************
    EOS
  end
end
